<link rel="icon" sizes="192x192" href="/public/images/NeptuneIcon192px.png">
<link rel="apple-touch-icon" href="/public/images/NeptuneIcon192px.png">
<link rel="shortcut icon" href="/public/images/favicon.png" type="image/x-icon" />

<link rel="stylesheet" href="/public/css/neptune.css" type="text/css" charset="utf-8">

<link rel="stylesheet" href="/public/editor/suneditor.min.css" type="text/css" charset="utf-8">
<script src="/public/editor/suneditor.min.js" type="text/javascript" charset="utf-8"></script>